"""add_units_table

Revision ID: 90c8a737dfe4
Revises: 143e87579da2
Create Date: 2026-07-26 07:41:57.505963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c8a737dfe4'
down_revision: Union[str, Sequence[str], None] = '143e87579da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('unit_system', sa.String(length=30), nullable=False),
    sa.Column('si_unit', sa.String(length=20), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('is_base_unit', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    op.create_index(op.f('ix_units_code'), 'units', ['code'], unique=True)
    op.create_index(op.f('ix_units_quantity'), 'units', ['quantity'], unique=False)
    op.create_index(op.f('ix_units_unit_system'), 'units', ['unit_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_unit_system'), table_name='units')
    op.drop_index(op.f('ix_units_quantity'), table_name='units')
    op.drop_index(op.f('ix_units_code'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
