"""Initial schema

Revision ID: 143e87579da2
Revises: 
Create Date: 2026-07-26 05:45:42.729581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143e87579da2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('organization', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('withdrawn_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standards'))
    )
    op.create_index(op.f('ix_standards_category'), 'standards', ['category'], unique=False)
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=True)
    op.create_index(op.f('ix_standards_organization'), 'standards', ['organization'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standards_organization'), table_name='standards')
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_index(op.f('ix_standards_category'), table_name='standards')
    op.drop_table('standards')
    # ### end Alembic commands ###
