"""KESE-S2-M3 add load calculation runs

Revision ID: 2019c1a33308
Revises: bc8032471425
Create Date: 2026-07-28 02:24:50.808149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2019c1a33308'
down_revision: Union[str, Sequence[str], None] = 'bc8032471425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_calculation_runs',
    sa.Column('calculation_key', sa.String(length=100), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.String(length=30), nullable=False),
    sa.Column('scenario', sa.String(length=30), nullable=False),
    sa.Column('run_status', sa.String(length=30), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('formula_version', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('result_snapshot', sa.JSON(), nullable=False),
    sa.Column('assumptions_snapshot', sa.JSON(), nullable=False),
    sa.Column('warnings_snapshot', sa.JSON(), nullable=False),
    sa.Column('standards_snapshot', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('calculated_by', sa.String(length=200), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejected_by', sa.String(length=200), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('supersedes_run_id', sa.Uuid(), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_status <> 'APPROVED' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL AND is_immutable = true)", name=op.f('ck_load_calculation_runs_approved_run_audit_complete')),
    sa.CheckConstraint("approval_status <> 'REJECTED' OR (rejected_by IS NOT NULL AND rejected_at IS NOT NULL AND rejection_reason IS NOT NULL)", name=op.f('ck_load_calculation_runs_rejected_run_audit_complete')),
    sa.CheckConstraint("approval_status IN ('NOT_SUBMITTED', 'PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_load_calculation_runs_approval_status_valid')),
    sa.CheckConstraint("calculation_type IN ('SINGLE_LOAD', 'LOAD_GROUP')", name=op.f('ck_load_calculation_runs_calculation_type_valid')),
    sa.CheckConstraint("is_immutable = false OR approval_status = 'APPROVED'", name=op.f('ck_load_calculation_runs_immutable_only_when_approved')),
    sa.CheckConstraint("run_status IN ('DRAFT', 'COMPLETED', 'FAILED')", name=op.f('ck_load_calculation_runs_run_status_valid')),
    sa.CheckConstraint("scenario IN ('NORMAL', 'EMERGENCY', 'OUTAGE', 'STARTING', 'UPS', 'PV', 'FUTURE')", name=op.f('ck_load_calculation_runs_scenario_valid')),
    sa.CheckConstraint('revision_number > 0', name=op.f('ck_load_calculation_runs_revision_number_positive')),
    sa.CheckConstraint('supersedes_run_id IS NULL OR supersedes_run_id <> id', name=op.f('ck_load_calculation_runs_run_cannot_supersede_itself')),
    sa.ForeignKeyConstraint(['supersedes_run_id'], ['load_calculation_runs.id'], name=op.f('fk_load_calculation_runs_supersedes_run_id_load_calculation_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_calculation_runs')),
    sa.UniqueConstraint('calculation_key', 'revision_number', name='calculation_key_revision_unique')
    )
    op.create_index(op.f('ix_load_calculation_runs_approval_status'), 'load_calculation_runs', ['approval_status'], unique=False)
    op.create_index(op.f('ix_load_calculation_runs_calculation_key'), 'load_calculation_runs', ['calculation_key'], unique=False)
    op.create_index(op.f('ix_load_calculation_runs_calculation_type'), 'load_calculation_runs', ['calculation_type'], unique=False)
    op.create_index(op.f('ix_load_calculation_runs_content_hash'), 'load_calculation_runs', ['content_hash'], unique=False)
    op.create_index('ix_load_calculation_runs_review_queue', 'load_calculation_runs', ['approval_status', 'created_at'], unique=False)
    op.create_index('ix_load_calculation_runs_revision_lookup', 'load_calculation_runs', ['calculation_key', 'scenario', 'revision_number'], unique=False)
    op.create_index(op.f('ix_load_calculation_runs_run_status'), 'load_calculation_runs', ['run_status'], unique=False)
    op.create_index(op.f('ix_load_calculation_runs_scenario'), 'load_calculation_runs', ['scenario'], unique=False)
    op.create_index(op.f('ix_load_calculation_runs_supersedes_run_id'), 'load_calculation_runs', ['supersedes_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_load_calculation_runs_supersedes_run_id'), table_name='load_calculation_runs')
    op.drop_index(op.f('ix_load_calculation_runs_scenario'), table_name='load_calculation_runs')
    op.drop_index(op.f('ix_load_calculation_runs_run_status'), table_name='load_calculation_runs')
    op.drop_index('ix_load_calculation_runs_revision_lookup', table_name='load_calculation_runs')
    op.drop_index('ix_load_calculation_runs_review_queue', table_name='load_calculation_runs')
    op.drop_index(op.f('ix_load_calculation_runs_content_hash'), table_name='load_calculation_runs')
    op.drop_index(op.f('ix_load_calculation_runs_calculation_type'), table_name='load_calculation_runs')
    op.drop_index(op.f('ix_load_calculation_runs_calculation_key'), table_name='load_calculation_runs')
    op.drop_index(op.f('ix_load_calculation_runs_approval_status'), table_name='load_calculation_runs')
    op.drop_table('load_calculation_runs')
    # ### end Alembic commands ###
