"""keos eos01b add project spine tables

Revision ID: b8e4f2a6c9d1
Revises: a7d3e9b1c5f2
Create Date: 2026-09-22 11:18:56.304166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e4f2a6c9d1'
down_revision: Union[str, Sequence[str], None] = 'a7d3e9b1c5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create sites, projects and project revisions (EOS-01 b)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code <> '' AND name <> ''", name=op.f('ck_sites_code_name_not_blank')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sites_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('organization_id', 'code', name='sites_organization_code_unique')
    )
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('jurisdiction_profile', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code <> '' AND name <> ''", name=op.f('ck_projects_code_name_not_blank')),
    sa.CheckConstraint("jurisdiction_profile IN ('IN', 'IEC', 'US', 'UK', 'AU_NZ', 'EU')", name=op.f('ck_projects_jurisdiction_valid')),
    sa.CheckConstraint("status IN ('ACTIVE', 'ARCHIVED')", name=op.f('ck_projects_status_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_projects_site_id_sites'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('organization_id', 'code', name='projects_organization_code_unique')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_site_id'), 'projects', ['site_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('project_revisions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('issued_by', sa.String(length=200), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("label <> ''", name=op.f('ck_project_revisions_label_not_blank')),
    sa.CheckConstraint("status <> 'ISSUED' OR (issued_by IS NOT NULL AND issued_at IS NOT NULL)", name=op.f('ck_project_revisions_issued_audit_complete')),
    sa.CheckConstraint("status IN ('OPEN', 'ISSUED', 'SUPERSEDED')", name=op.f('ck_project_revisions_status_valid')),
    sa.CheckConstraint('revision_number > 0', name=op.f('ck_project_revisions_revision_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_revisions_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_revisions')),
    sa.UniqueConstraint('project_id', 'revision_number', name='project_revisions_project_number_unique')
    )
    op.create_index(op.f('ix_project_revisions_project_id'), 'project_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_revisions_status'), 'project_revisions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop project revisions, projects and sites."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_revisions_status'), table_name='project_revisions')
    op.drop_index(op.f('ix_project_revisions_project_id'), table_name='project_revisions')
    op.drop_table('project_revisions')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_site_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
