"""keos eos01b link calculation runs to project revisions

Revision ID: c9f5a3b7d2e4
Revises: b8e4f2a6c9d1
Create Date: 2026-09-22 12:53:02.981611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f5a3b7d2e4'
down_revision: Union[str, Sequence[str], None] = 'b8e4f2a6c9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Link calculation runs to project revisions and split the study key per scope (EOS-01 b).

    Existing rows keep project_revision_id NULL: every run made before this release belongs to
    no project (A14) and stays under the unassigned key, so no data is migrated here.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_runs', sa.Column('project_revision_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('calculation_runs_key_revision_unique'), 'calculation_runs', type_='unique')
    op.create_index(op.f('ix_calculation_runs_project_revision_id'), 'calculation_runs', ['project_revision_id'], unique=False)
    op.create_index('uq_calculation_runs_project_key', 'calculation_runs', ['project_revision_id', 'module_code', 'calculation_key', 'revision_number'], unique=True, postgresql_where=sa.text('project_revision_id IS NOT NULL'), sqlite_where=sa.text('project_revision_id IS NOT NULL'))
    op.create_index('uq_calculation_runs_unassigned_key', 'calculation_runs', ['module_code', 'calculation_key', 'revision_number'], unique=True, postgresql_where=sa.text('project_revision_id IS NULL'), sqlite_where=sa.text('project_revision_id IS NULL'))
    op.create_foreign_key(op.f('fk_calculation_runs_project_revision_id_project_revisions'), 'calculation_runs', 'project_revisions', ['project_revision_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore the single unique key over (module_code, calculation_key, revision_number).

    Limit of this downgrade: the old constraint knows nothing about project revisions, so it
    fails when runs of different revisions share a study key and revision number - which is
    exactly what the upgrade allows. Such rows have to be removed or renumbered by hand first;
    the downgrade refuses rather than dropping evidence. Back the database up before either
    direction.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_calculation_runs_project_revision_id_project_revisions'), 'calculation_runs', type_='foreignkey')
    op.drop_index('uq_calculation_runs_unassigned_key', table_name='calculation_runs', postgresql_where=sa.text('project_revision_id IS NULL'), sqlite_where=sa.text('project_revision_id IS NULL'))
    op.drop_index('uq_calculation_runs_project_key', table_name='calculation_runs', postgresql_where=sa.text('project_revision_id IS NOT NULL'), sqlite_where=sa.text('project_revision_id IS NOT NULL'))
    op.drop_index(op.f('ix_calculation_runs_project_revision_id'), table_name='calculation_runs')
    op.create_unique_constraint(op.f('calculation_runs_key_revision_unique'), 'calculation_runs', ['module_code', 'calculation_key', 'revision_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('calculation_runs', 'project_revision_id')
    # ### end Alembic commands ###
