"""
Pydantic schemas for persistent electrical calculation runs.
KESE-S2-M3
"""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
)

from kes_electrical_core.loads.models import LoadScenario
from app.models.load_calculation_run import (
    CalculationApprovalStatus,
    CalculationRunStatus,
    CalculationRunType,
)


def _validate_json_value(
    value: object,
    *,
    path: str,
) -> None:
    """
    Validate that a snapshot contains JSON-safe exact values.

    Binary floating-point values are rejected. Engineering decimal
    values must already be serialized as strings.
    """

    if value is None:
        return

    if isinstance(value, bool):
        return

    if isinstance(value, int):
        return

    if isinstance(value, str):
        return

    if isinstance(value, float):
        raise ValueError(
            f"{path} must not contain floating-point values; "
            "serialize engineering decimals as strings"
        )

    if isinstance(value, dict):
        for key, nested_value in value.items():
            if not isinstance(key, str):
                raise ValueError(
                    f"{path} must contain only string object keys"
                )

            _validate_json_value(
                nested_value,
                path=f"{path}.{key}",
            )

        return

    if isinstance(value, (list, tuple)):
        for index, nested_value in enumerate(value):
            _validate_json_value(
                nested_value,
                path=f"{path}[{index}]",
            )

        return

    raise ValueError(
        f"{path} contains a non-JSON-compatible value "
        f"of type {type(value).__name__}"
    )


class _RequestBase(BaseModel):
    """Shared configuration for calculation-run requests."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )


class _ResponseBase(BaseModel):
    """Shared configuration for calculation-run responses."""

    model_config = ConfigDict(
        from_attributes=True,
        extra="forbid",
    )


class LoadCalculationRunCreate(_RequestBase):
    """
    Request for persisting a completed or failed calculation run.

    Revision number, content hash and previous-revision linkage are
    generated by the service layer.
    """

    calculation_key: str = Field(
        min_length=1,
        max_length=100,
    )

    calculation_type: CalculationRunType

    scenario: LoadScenario

    run_status: CalculationRunStatus = (
        CalculationRunStatus.COMPLETED
    )

    engine_version: str = Field(
        min_length=1,
        max_length=50,
    )

    formula_version: str = Field(
        min_length=1,
        max_length=50,
    )

    input_snapshot: dict[str, Any] = Field(
        min_length=1,
    )

    result_snapshot: dict[str, Any] = Field(
        min_length=1,
    )

    assumptions_snapshot: dict[str, Any] = Field(
        default_factory=dict,
    )

    warnings_snapshot: list[dict[str, Any]] = Field(
        default_factory=list,
    )

    standards_snapshot: list[dict[str, Any]] = Field(
        default_factory=list,
    )

    calculated_by: str | None = Field(
        default=None,
        max_length=200,
    )

    notes: str | None = None

    @field_validator(
        "input_snapshot",
        "result_snapshot",
        "assumptions_snapshot",
        "warnings_snapshot",
        "standards_snapshot",
        mode="before",
    )
    @classmethod
    def validate_snapshots(
        cls,
        value: object,
    ) -> object:
        """Reject non-JSON and binary floating-point snapshot values."""

        _validate_json_value(
            value,
            path="snapshot",
        )

        return value


class LoadCalculationRunSubmit(_RequestBase):
    """Request for submitting a calculation run for review."""

    submitted_by: str = Field(
        min_length=1,
        max_length=200,
    )


class LoadCalculationRunApprove(_RequestBase):
    """Request for approving and locking a calculation run."""

    approved_by: str = Field(
        min_length=1,
        max_length=200,
    )

    approval_notes: str | None = None


class LoadCalculationRunReject(_RequestBase):
    """Request for rejecting a calculation run."""

    rejected_by: str = Field(
        min_length=1,
        max_length=200,
    )

    rejection_reason: str = Field(
        min_length=1,
    )


class LoadCalculationRunResponse(_ResponseBase):
    """Complete persistent calculation-run audit response."""

    id: UUID

    calculation_key: str
    revision_number: int

    calculation_type: CalculationRunType
    scenario: LoadScenario
    run_status: CalculationRunStatus
    approval_status: CalculationApprovalStatus

    engine_version: str
    formula_version: str

    input_snapshot: dict[str, Any]
    result_snapshot: dict[str, Any]
    assumptions_snapshot: dict[str, Any]
    warnings_snapshot: list[dict[str, Any]]
    standards_snapshot: list[dict[str, Any]]

    content_hash: str | None

    calculated_by: str | None
    calculated_at: datetime
    completed_at: datetime | None

    submitted_by: str | None
    submitted_at: datetime | None

    approved_by: str | None
    approved_at: datetime | None
    approval_notes: str | None

    rejected_by: str | None
    rejected_at: datetime | None
    rejection_reason: str | None

    supersedes_run_id: UUID | None
    is_immutable: bool

    notes: str | None

    created_at: datetime
    updated_at: datetime


class LoadCalculationRunComparisonResponse(_ResponseBase):
    """Comparison between two revisions of one calculation."""

    calculation_key: str

    base_run_id: UUID
    base_revision_number: int

    target_run_id: UUID
    target_revision_number: int

    input_differences: dict[str, Any]
    result_differences: dict[str, Any]
    audit_differences: dict[str, Any]


__all__ = [
    "LoadCalculationRunApprove",
    "LoadCalculationRunComparisonResponse",
    "LoadCalculationRunCreate",
    "LoadCalculationRunReject",
    "LoadCalculationRunResponse",
    "LoadCalculationRunSubmit",
]
